### PR TITLE
Add inline annotations

### LINKED ISSUE #5: Allow reporting annotations without creating a new check
Right now this action adds a new check to report all annotations. Ideally I'd want to disable this behavior and just report annotations "normally" like other actions do.

For example, one of the linters I use is markdownlint and I enabled a problem matcher for that to create annotations. Another one is [yutailang0119/action-android-lint](https://github.com/yutailang0119/action-android-lint) that uses the GitHub actions toolkit to create the annotations from a Android XML file.

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
This adds "inline annotations". It uses the warning and error commands documented here: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message
GitHub will only report the first 10 found.

Closes #5 

Depends on #8

### CODE REVIEW

**Comment by jwgmeligmeyling** [comment]
Nice addition! Do you have a screenshot how these inline annotations look?

**Comment by nielsvanvelzen** [comment]
You can see an example of it in the actions from this PR since I added a test for it.

**Comment by jwgmeligmeyling** [comment]
The build is still failing (the test matrix). I don't have time to look into it. Hopefully @Scottmitch is able to finish up his PR, so I can merge all three of the PR's.

**Comment by nielsvanvelzen** [comment]
I'm closing this PR to keep my list of open PR's clean, feel free to use my changes or re-open when the dependent PR is merged.

**Pull request closed without merging**
